name: Deploy para Netlify no Windows Exercicio Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Netlify CLI
        run: npm install -g netlify-cli
        shell: pwsh

      - name: Deploy para Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --site=$env:NETLIFY_SITE_ID --auth=$env:NETLIFY_AUTH_TOKEN --dir="." --prod
        shell: pwsh
